### ISSUE TITLE
WIP: Third event

### ISSUE THREAD

**Issue by hamidrezakp** [rust-meetup/rust-meetup.github.io#1]
# Todo

- [x] Settle for a date and location: **Fri 2021-12-17, 21:00 IRST**
- [ ] Find a Presenter or some other idea for meetup
- [ ] Send "Save the Date" info (with link to this ticket) to twitter and telegram
- [ ] Basic Agenda (default: Open Space or a presentation)
- [ ] Final invitation (deadline **Mon 2021-12-13, 00:00 IRST**)
  - [ ] [website]
  - [ ] [twitter]
  - [ ] [community calendar]
  - [ ] [reddit]
  - [ ] [rust-lang forum]

# Invitation draft

```markdown
Title: ###: Save The Date

Dear Rustaceans,

our next Meetup will be on **Fri 2021-12-17, 21:00 IRST**.

**Some Text for here**

**[You can register here - Add link here](...)**.

We are looking forward to seeing you. :-)

Yours,
Rust Iran Meetup
```
