### ISSUE TITLE
Meetup #06 Todo List

### ISSUE THREAD

**Issue by hamidrezakp** [rust-meetup/rust-meetup.github.io#2]
# Todo

- [ ] Settle for a date: **Friday YYYY-MM-DD, 21:00 IRST**
- [ ] Find a presenter or choose a topic for meetup talk
- [ ] Make poster with info and dates on it
- [ ] Add meetup details on website (default: [Rust Meetup](https://rust-meetup.ir))
- [ ] Post poster and details on social media
  - [ ] [telegram](https://t.me/RustLand)
  - [ ] [twitter](https://twitter.com/Rust_ir)
  - [ ] [community calendar](https://calendar.google.com/calendar/embed?showTitle=0&showPrint=0&showTabs=0&showCalendars=0&mode=AGENDA&height=400&wkst=1&bgcolor=%23FFFFFF&src=apd9vmbc22egenmtu5l6c5jbfc%40group.calendar.google.com&color=%23691426&ctz=Europe%2FMadrid)
  - [ ] [Email List] Not created yet!
- [ ] Add recordings
- [ ] Upload to [Youtube]
- [ ] Upload to [Aparat]
- [ ] Update meetup post on website (default: [Rust Meetup](https://rust-meetup.ir))
- [ ] Post recording links in social media
  - [ ] [telegram](https://t.me/RustLand)
  - [ ] [twitter](https://twitter.com/Rust_ir)
  - [ ] [Email List] Not created yet!
